name: Déployer en prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: burnett01/rsync-deployments@5.2.1
      with:
        source: "."
        destination: "debian@51.178.28.180:/home/debian/pizza"
        flags: "az"
        exclude: ".git,node_modules"
        delete: true
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}