name: Déplotest runyer en prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ secrets.DEPLOY_KEY }}" > key.rsa \
        rsync -avz -e "ssh -i ./key.rsa" /local/path user@remote:/home/debian/pizza
    - uses: actions/checkout@v2
    # - name: rsync deployments
    #   uses: burnett01/rsync-deployments@5.2.1
    #   with:
    #     switches: -avzr --delete
    #     path: ./
    #     remote_path: /home/debian/pizza/
    #     remote_host: ${{ secrets.REMOTE_HOST }}
    #     remote_user: debian
    #     remote_key: ${{ secrets.DEPLOY_KEY }}
    #     rsh: "echo ${{ secrets.DEPLOY_KEY }} > ip.txt;"
